name = "Ratafia's mod"
description = "The minimalist mod to help novices find each other in the don't starve together world using a get position button to get current coordinates without further map mods. find touchstone button returns the coordinates of the nearest touchstone and the character will turn its face to it."
author = 'Ratafia'
version = '0.0.3'
forumthread = '/'
client_only_mod = true
dont_starve_compatible = true
reign_of_giants_compatible = true
dst_compatible = true
api_version = 10